### PR TITLE
POL-621 Use Kafka SASL configuration from Clowder

### PR DESCRIPTION
**Pull request by gwenneg**
This is needed to finish the Clowder migration on fedramp-stage.

### CODE REVIEW

**Comment by pilhuhn** [comment]
I guess it is ok. I would have preferred 2 prs: one for the json parsing changes and another one to add the Kafka SASL parsing/retrieving

**Comment by gwenneg** [comment]
Ok I'll split this PR.

**Comment by pilhuhn** [comment]
You don't have to

**Comment by gwenneg** [comment]
Ok then I won't but I'll create separate PRs if a similar situation happens in the future 😄

**Comment by gwenneg** [comment]
FYI the JSON parsing changes were motivated by this in `ClowderConfigSource`:
```
Optional<BrokerConfig> saslBroker = root.kafka.brokers.stream()
        .filter(broker -> "sasl".equals(broker.authtype))
        .findAny();
```

**Review by josejulio — APPROVED** [review]

**Pull request merged**
